version: '3'
services:
  database:
    image: postgres:15.2-alpine
    container_name: database
    networks:
      - postgres
    volumes:
      - ./data/_postgres:/data/postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - ./data/_pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - ./data/_redis:/data/redis
    ports:
      - '6379:6379'

  core:
    container_name: core-microservices
    build:
      context: .
      dockerfile: ./core/Dockerfile
    ports:
      - "${CORE_PORT}:3000"
    volumes:
      - ${PWD:-./core}:/app/core
    networks:
      - postgres
    command: sh -c "yarn && yarn build && yarn start:dev"

  gateway:
    container_name: gateway-microservices
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:4000"
    volumes:
      - ${PWD:-./gateway}:/app/gateway
    command: sh -c "yarn && yarn build && yarn start:dev"

networks:
  postgres:
    driver: bridge
