version: '3'
services:
  postgres:
    image: postgres:15.2-alpine
    networks:
      - postgres
    volumes:
      - ./data/_postgres:/data/postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - ./data/_pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - ./data/_redis:/data/redis
    ports:
      - '6379:6379'

  app:
    build: ./
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
